# Generated by Django 3.2.3 on 2021-05-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='None', max_length=255),
            preserve_default=False,
        ),
    ]
